---
title: "Data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset.

```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv")
```

Look at your data!!

```{r}
names(litters_df)
```

Update the names in 'litters_df'.

```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

Look at the data.

```{r}
litters_df
```

Sometims skiming data is neat?

```{r}
skimr::skim(litters_df)
```

## Fix the missingness

```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))
```

Learning assessment 1

```{r}
pups_df =
  read_csv(
    "data_import_examples/FAS_pups.csv",
    skip = 3,
    na = c("NA", ".", "")
  )

pups_df = 
  janitor::clean_names(pups_df)
```

## What about excel

```{r}
mlb_df = 
  read_excel("data_import_examples/mlb11.xlsx")
```

Import LotR word counts.

```{r}
fotr_df = 
  read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

## SAS?

Import the PULSE dataset.

```{r}
pulse_df = read_sas("data_import_examples/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)
```

## Why does he hate read.csv so much?

```{r, eval = FALSE}
litters_df_base =
  read.csv("data_import_examples/FAS_litters.csv")
```

## What about data exporting?

```{r}
write_csv(fotr_df, "data_import_examples/fotr_df.csv")
```





